//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClarityAid.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClarityAid.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   namespace Clarity.Engine
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Clarity Engine Aid Class
        ///    /// &lt;/summary&gt;
        ///    public static partial class ClarityAid
        ///    {
        ///        __AID_CODE__
        ///    }
        ///} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AidCode {
            get {
                return ResourceManager.GetString("AidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;ClarityCodeAid&gt;
        ///	&lt;Texture&gt;
        ///		public static void SetTexture(this Clarity.Engine.RendererSet set, ETextureID etex, int slot = 0)
        ///        {
        ///            set.SetTextureId(slot, (int)etex);
        ///        }
        ///	&lt;/Texture&gt;
        ///	&lt;Vertex&gt;
        ///	&lt;/Vertex&gt;
        ///	&lt;Shader&gt;
        ///	&lt;/Shader&gt;
        ///	&lt;Sound&gt;
        ///	&lt;/Sound&gt;
        ///	&lt;ImageMerge&gt;
        ///	&lt;/ImageMerge&gt;
        ///	&lt;TextureAnime&gt;
        ///	&lt;/TextureAnime&gt;
        ///	&lt;Structure&gt;
        ///		public static void AddElement(EClarityStructureID id, Clarity.Element.BaseElement data)
        ///		{
        ///			Clarity.Eng [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AidFunc {
            get {
                return ResourceManager.GetString("AidFunc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   namespace Clarity.Engine
        ///{
        ///    /// &lt;summary&gt;
        ///    /// __CLASS_DESC__
        ///    /// &lt;/summary&gt;
        ///    public class __CLASS_NAME__ 
        ///    {
        ///__MEMBER_CODE__
        ///    }
        ///
        ///__AID_FUNC__
        ///} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ClassCode {
            get {
                return ResourceManager.GetString("ClassCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   namespace Clarity.Engine
        ///{
        ///    /// &lt;summary&gt;
        ///    /// __CLASS_DESC__
        ///    /// &lt;/summary&gt;
        ///    public enum __CLASS_NAME__ : int
        ///    {
        ///__MEMBER_CODE__
        ///    }
        ///
        ///    __AID_FUNC__
        ///} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EnumCode {
            get {
                return ResourceManager.GetString("EnumCode", resourceCulture);
            }
        }
    }
}
