//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clarity.Engine.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Clarity.Engine.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   struct VS_IN
        ///{
        ///	float4 pos : POSITION;
        ///	float4 col : COLOR;
        ///	float2 tex : TEXCOORD;
        ///};
        ///
        ///
        ///struct PS_IN
        ///{
        ///	float4 pos : SV_POSITION;
        ///	float4 col : COLOR;
        ///	float2 tex : TEXCOORD;
        ///};
        ///
        ///
        ///struct RegistData
        ///{
        ///	float4x4 WorldViewProj;
        ///	float4 Col;
        ///	float2 tex_div;
        ///	float2 tex_offset;
        ///
        ///};
        ///
        ///RegistData RData : register(s0);
        ///
        /////�e�N�X�`��
        ///Texture2D pix : register(t0);
        ///SamplerState picsamp : register(s1);
        ///
        ///
        ////////////////////////////////////////////////////////////////////////////////////// [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SDef {
            get {
                return ResourceManager.GetString("SDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap T0000 {
            get {
                object obj = ResourceManager.GetObject("T0000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap T0001 {
            get {
                object obj = ResourceManager.GetObject("T0001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   V3C3T2
        ///4
        ///-0.5,	1.0,	0.0,	1.0,	1.0,	1.0,	1.0,	0.0
        ///0.5,	1.0,	0.0,	1.0,	1.0,	1.0,	0.0,	0.0
        ///0.5,	0.0,	0.0,	1.0,	1.0,	1.0,	0.0,	20.0
        ///-0.5,	0.0,	0.0,	1.0,	1.0,	1.0,	1.0,	20.0
        ///2
        ///0,1,2
        ///0,2,3
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string VLine {
            get {
                return ResourceManager.GetString("VLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   V3C3T2
        ///4
        ///-0.5,	0.5,	0.0,	1.0,	1.0,	1.0,	1.0,	0.0
        ///0.5,	0.5,	0.0,	1.0,	1.0,	1.0,	0.0,	0.0
        ///0.5,	-0.5,	0.0,	1.0,	1.0,	1.0,	0.0,	1.0
        ///-0.5,	-0.5,	0.0,	1.0,	1.0,	1.0,	1.0,	1.0
        ///2
        ///0,1,2
        ///0,2,3
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string VRect {
            get {
                return ResourceManager.GetString("VRect", resourceCulture);
            }
        }
    }
}
